---
title: Taxation of returns
jupyter:
  kernelspec:
    display_name: acct3210
    language: python
    name: acct3210
format: 
  revealjs:
    css: custom-styles.css
    scrollable: true
---

## Three things that I'd like to acknowledge:
1. The assignment focuses on personal finance examples with relatively complex formulae that are not the point of the exercise.
2. The examples are U.S. focused.
3. More interesting examples would also include jurisdiction choices, like the choice to operate in Hong Kong rather than the U.S. or Europe. (We will do a case like this soon) 

## Why think about non-Hong Kong tax rates? 

_Hong Kong is a low tax rate jurisdiction, so this foreign tax rates will be very relevant... __especially__ if you plan to work in Hong Kong._

Taxes shape behavior _explicitly_ by decreasing demand for investments that are taxed relative to those that are not, and _implicitly_ by increasing the cost (lowering yield) of those investments that are not taxed.

In addition to investment choices, __organizational form arbitrage__ and __clientele-based arbitrage__ are ways that taxes shape behavior.

## High-level insights from the lecture:

1. Tax rates impact returns.
    - Not just net-of-tax returns, but __returns themselves__.
2. Tax rates vary across individuals, jurisdictions, and investments. These differences change choices, and demand for assets.
3. This creates variation in demand, and yield, for investments and jurisdictions. These are implicit taxes.

## 1. Tax rates and implicit taxes

Let's think about the following situation:

- Companies issue bonds to raise capital, the interest rate ($r_B$) (base rate + credit spread) on these bonds is called 'bond yield'. Bond yield is income for the holder of the bond (the 'lender'). 
    - This income is taxed by U.S. States ($t_{S}$) and the U.S. Federal Government ($t_{F}$).
- The U.S. Treasury issues bonds to raise capital, the yield on these bonds ($r_{T}$) is also income for the holder of the bond.
    - This income is _only_ taxed by the U.S. Federal Government ($t_{F}$) but not by U.S. States.

## An aside on tax rates

Yes, you read that right. If you lend money to the U.S. Government, they tax the interest that they pay you, but they do not let the states tax you (that makes sense, you didn't earn that money _in_ the state where you live).

The reverse is also true, so:

- State and Local Bonds only pay state tax: $t_{S}$
- Federal Bonds only pay Federal Tax: $t_{F}$

Now, what is important here is that we have a real example with different tax rates on similar investments. _Not the details of the U.S. tax system, which is __insane__._ Examples like this are harder to come by in more sensible tax regimes like Hong Kong :)

## 1. Tax rates and implicit taxes

So we have two bonds (corporate, and US Federal) with two yields, taxed at two rates.

- Corp. Bond Pretax Yield: $r_{B}$ Taxed at $t_{F}$ then $t_{S}$.
    - Corp. After Tax Yield: 
$$r_{B'}=r_{B}(1-t_{F}-t_{S}(1-t_{F}))$$
$$r_{B'}=r_{B}(1 - t_{F})(1 - t_{S})$$

- US Treas. Bond Pretax Yield: $r_{T}$. Taxed at $t_{F}$.
    - US Treas. After Tax Yield:
$$r_{T'}=r_{T}(1 - t_{F})$$

## 1. Tax rates and implicit taxes

### So if $r_B=r_T$ which do you prefer? 

- $r_{B'}=r_{B}(1 - t_{F})(1 - t_{S})$
- $r_{T'}=r_{T}(1 - t_{F})$

__It depends on $t_S$.__


## [US Tax Rates by State](https://en.wikipedia.org/wiki/State_income_tax#/media/File:Top_Marginal_State_Income_Tax_Rate.svg)

## 1. Tax rates and implicit taxes

If $r_B=r_T$ and $t_S=0$ then $r_{B'}=r_{T'}$

So for investors that are located in Alaska, Florida, Nevada, South Dakota, Tennessee, Texas, Washington, and Wyoming there is no difference between the two.

But for most of the population of the US $t_S>0$ so $r_{B'}<r_{T'}$! 

- Given what we know about markets, what does this suggest about the relationship between corporate bond yields ($r_B$) and US Treasury yields ($r_T$) on average? I.e. which is higher on average?

## 1. Tax rates and implicit taxes

- Tax favored status increases demand for assets, increased demand decreases yields.
- So on average $r_B>r_T$ because there is more demand for Treasury bonds. 
- You can think of this as companies having to pay higher rates to get people to lend to them (i.e. buy their bonds).

This difference in yields caused by the impact of tax-favored status is called an __implicit tax__.

## 1. Tax rates and implicit taxes

- __Explicit Taxes__ reduce after tax yields directly.
- __Implicit Taxes__ reduce pre-tax yields through demand pressure.

$$ Implicit\;Tax\;Rate = \frac{Benchmark\;Return - Asset\;Return}{Benchmark\;Return}$$

where the benchmark is an investment with the same risk.

The higher are state taxes, the more attractive Treasury securities become.
Demand for Treasuries pushes their yield down. This example is an illustration
of tax clienteles. It also shows that ignoring implicit taxes leads to
overestimation of the risk premium applicable to corporate debt.


## Bond example:

|               | Coupon | Maturity | Price   | Yield |
|---------------|--------|----------|---------|-------|
| Amoco Aaa/AAA | 8.625  | 12/2016  | 105.953 | 8.060 |
| U.S. Gov      | 7.5    | 11/2016  | 99.4375 | 7.55  |

Ignoring the differences in risk, the implicit tax is:

$$\frac{8.060-7.55}{8.060}=6.3\%$$

Questions:

- Which assets should a pension invest in? (Only proceeds from pensions are taxed)
- Which asset should a resident of Florida or Texas invest in? (These states have no income tax)
- Which asset should a resident of California, Minnesota, or New York invest
  in? (These states have income tax, but do not tax interest income from U.S. Government bonds.)

# 2. Tax Rate Progressivity

Progressive tax rates increase with income.

How progressive are tax rates? The answer you reach depends on where you look for evidence.

## 2.1 Enacted Tax Rates

- Explicit tax rates are often sharply progressive. In the United States at various times, income tax rates have ranged between zero and 70 percent, suggesting that tax rates are very progressive.

## 2.2 Tax Returns

- For low income, low tax rate taxpayers, the amount of explicit tax paid to the taxing authority as a fraction of income may be quite large.
- The fraction may even be higher than the corresponding fraction for wealthy, high income individuals. 
- For instance, a very wealthy individual may have a large investment in municipal bonds on which no tax is paid to the Treasury. 
- This suggests that taxes are, in fact, not very progressive.

## 2.3 Combined Productivity

- By considering the sum of explicit and implicit taxes paid by each taxpayer, it becomes apparent that substantial implicit taxes are often paid by high tax rate taxpayers in place of explicit taxes that would be even greater.

- Thus, tax rates are more progressive than an examination of tax returns would suggest, but less progressive than enacted tax rates would suggest.

- The erosion of the progressivity in enacted tax rates depends upon the nature and availability of differentially taxed assets that investors facing varying marginal taxes may choose to trade.


# 3. Arbitrage

## 3.1 __organizational form arbitrage__
The process of taking a long position in an asset or activity through a _favorably_ taxed organizational form, and a short position in an through an _unfavorably_ taxed organizational form.

If there are no limits on __organizational form arbitrage__, then all taxes can be eliminated.



## Examples:

- Pensions and certain life insurance policies are organizational forms that are favorably taxed.
- To eliminate taxes on personal income earned outside these vehicles there are two possible strategies. 
  
Suppose you anticipate salary income in the future which you wish to shelter from tax.



## Insurance policy strategy

1. Issue tax-deductible debt on personal account. (i.e. get a student loan) 
2. Use the proceeds to buy __similar__ taxable bonds inside the insurance policy. 
3. Borrow enough money so that the interest deductions equal taxable salary. 
4. Surrender the policy for its cash value and receive tax-free a payment equal to the principal and interest due on your borrowings.

_Limited by your access to deductible interest._

## Pension strategy

1. Contribute all of your taxable income to the pension.  
2. Then borrow for current consumption needs. 
3. Secure your borrowings with the pension assets. 
4. Repay your borrowings when you draw on your pension. 
5. You pay no tax on the funds distributed from the pension because you have unused interest expense deductions from your borrowings.

_Limited by your access to deductible interest._

## 3.2 __clientele-based arbitrage__

High-tax-rate organizations take long positions in tax-favored assets (these assets bear implicit taxes), and short positions in tax-disfavored assets (explicitly taxed).

[Low-tax-rate organizations take the opposite positions.](https://www.ird.gov.hk/eng/tax/bus_qdi.htm)

If there are no limits on clientele-based arbitrage, then all taxpayers must face the same marginal rate of tax, namely zero!

## Example:

- Suppose a taxable bond yields $R_B = 10\%$ and a muni (municipal) bond yields $R_M =7\%$.
- Tax exempt universities and municipalities issue munis and buy taxable bonds so long as
$$R_B > R_M$$
- __This drives down the yield on corporate bonds__

### Implications: 

- Each tax-exempt organization able to issue munis wants to buy taxable bonds. 
- So the marketplace is flooded with muni debt issued by the tax-exempt entities, so the yield offered on munis has to rise.
- When the pre-tax yields on munis and taxable debt equilibrate, say at 8%, then it becomes possible for all entities that face a positive explicit rate of tax to generate sufficient deductions to eliminate all tax payments.

## The Strategy:

__The strategy used by taxpayers who would otherwise have taxable income is as follows:__

- Issue taxable bonds at 8%. 
- Each dollar of debt issued generates 8 cents of tax deductions that can be used to reduce other taxable income. 
- The proceeds from the debt issue are invested in tax-exempt muni bonds, so cash flows from borrowing and lending wash.

# "Alternative Savings Vehicles"

## Question 1:

Fill in the table. Notice that tasks which lend themselves to tabular comparisons, especially when we only need to consider a few outcomes, are where Excel really shines.

However, we always need to be attentive to Excel's ability to hide errors.

## Question 2:

> How do optimal investment strategies change as a function of tax rates, lengths of investment horizon, and age?

- __Tax rates:__ In general, high tax rate decision makers prefer tax exempt vehicles.
- __Horizon:__ As horizon increases investors prefer SPDAs. Notice that at the 20 year horizon the penalty is still preferred.
- __Age:__ The probability of early withdrawal is decreasing with age, thus the SPDA becomes more attractive.

## Question 3:

Focus on the timing of cashflows and the payments avoided.

## Question 4:

Now we loose the benefit of the tax deduction.
