<!DOCTYPE html>
<html lang="en"><head>
<script src="costallocation_slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="costallocation_slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="costallocation_slides_files/libs/quarto-html/popper.min.js"></script>
<script src="costallocation_slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="costallocation_slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="costallocation_slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="costallocation_slides_files/libs/quarto-html/quarto-syntax-highlighting-97af773cfbe0d0670e77fe96929c7f4c.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.40">

  <meta name="author" content="Dr.&nbsp;Arthur Morris">
  <title>Cost Allocation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="costallocation_slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="costallocation_slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="costallocation_slides_files/libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link rel="stylesheet" href="custom-styles.css">
  <link href="costallocation_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="costallocation_slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="costallocation_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="costallocation_slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Cost Allocation</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Arthur Morris 
</div>
        <p class="quarto-title-affiliation">
            HKUST School of Business and Management
          </p>
    </div>
</div>

</section>
<section id="transfer-pricing" class="slide level2">
<h2>Transfer pricing</h2>
<ul>
<li>Transfer pricing is the process of using a price to facilitate decentralized decision making by sharing information and aligning incentives within the firm.</li>
</ul>
</section>
<section id="transfer-pricing-1" class="slide level2">
<h2>Transfer pricing</h2>
<ul>
<li>In simple examples like the initial questions in the Vik-Giger case it is easy to figure out what the price of a product should be.</li>
</ul>
</section>
<section id="transfer-pricing-2" class="slide level2">
<h2>Transfer pricing</h2>
<ul>
<li>In that case we took for granted that we could easily quantify the costs of making the product.</li>
<li>We also noted that transferring fixed costs (those that do not vary with output) is not at all simple… but we didn’t do anything about it.</li>
<li>Cost allocation is the process of quantifying the costs of making a product.</li>
</ul>
</section>
<section id="cost-allocation" class="slide level2">
<h2>Cost allocation</h2>
<ul>
<li>Cost allocation is the process of connecting the sacrifice of resources (often a cash outflow) to the process, product, program, or department on behalf of which the resources were sacrificed.</li>
</ul>
</section>
<section id="cost-allocation-1" class="slide level2">
<h2>Cost allocation</h2>
<ul>
<li>We are trying to track who consumed which resources and when.</li>
<li>We do this for many reasons and in many different contexts, so there is no one approach that is better in every situation.</li>
</ul>
</section>
<section id="cost-allocation-2" class="slide level2">
<h2>Cost allocation</h2>
<ul>
<li>Note that transfer pricing requires cost allocation, but not all cost allocations are done to support transfer pricing.</li>
</ul>
</section>
<section id="which-costs" class="slide level2">
<h2>Which costs?</h2>
<ul>
<li>We want to track all costs, but cost allocations focus on <em>common, indirect, and overhead costs</em> (all related terms)</li>
<li>We allocate direct costs <strong>directly</strong> to the activities or products that consume them.</li>
</ul>
</section>
<section id="cost-allocation-3" class="slide level2">
<h2>Cost allocation</h2>
<ul>
<li>Most costs are direct at some point, and then flow into an area of the organization where they become indirect.</li>
<li>For example, a networking department has many direct costs, but many departments access it indirectly.</li>
</ul>
</section>
<section id="consider-email" class="slide level2">
<h2>Consider email</h2>
<ul>
<li>we can easily track who uses it.</li>
<li>we have good information about how much it costs.</li>
<li>but it is difficult to define the relationship between email use and value creation in the design, manufacturing and sales department.</li>
</ul>
</section>
<section id="consider-aspirin-administered-in-an-american-hospital" class="slide level2">
<h2>Consider aspirin administered in an American Hospital</h2>
<ul>
<li>Aspirin costs $ 0.02 per tablet.</li>
<li>How much is billed to the patient/insurer?</li>
</ul>
</section>
<section id="consider-aspirin-administered-in-an-american-hospital-1" class="slide level2">
<h2>Consider aspirin administered in an American Hospital</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Direct Costs</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two aspirin tablets</td>
<td style="text-align: right;">$ 0.040</td>
</tr>
<tr class="even">
<td>Physician (Direct Labor)</td>
<td style="text-align: right;">$ 1.050</td>
</tr>
<tr class="odd">
<td>Pharmacist (Direct Labor)</td>
<td style="text-align: right;">$ 1.330</td>
</tr>
<tr class="even">
<td>Nurse (Direct Labor)</td>
<td style="text-align: right;">$ 0.321</td>
</tr>
<tr class="odd">
<td>Cup</td>
<td style="text-align: right;">$ 0.025</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indirect Costs</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Indirect labor (recordkeeping and orderly)</td>
<td style="text-align: right;">$ 0.800</td>
</tr>
<tr class="even">
<td>Shared and shifted costs:</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Unreimbursed Medicare</td>
<td style="text-align: right;">$ 0.450</td>
</tr>
<tr class="even">
<td>Indigent care</td>
<td style="text-align: right;">$ 0.332</td>
</tr>
<tr class="odd">
<td>Malpractice insurance and uncollectible receivables</td>
<td style="text-align: right;">$ 0.380</td>
</tr>
<tr class="even">
<td>Excess bed capacity</td>
<td style="text-align: right;">$ 0.429</td>
</tr>
<tr class="odd">
<td>Other administrative and operating costs</td>
<td style="text-align: right;">$ 0.688</td>
</tr>
<tr class="even">
<td><strong>Product cost</strong></td>
<td style="text-align: right;"><strong>$ 5.845</strong></td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Hopital Overhead Costs</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Product cost</td>
<td style="text-align: right;">$ 5.845</td>
</tr>
<tr class="even">
<td>Hospital overhead costs @ 53.98%</td>
<td style="text-align: right;">$ 3.16</td>
</tr>
<tr class="odd">
<td>Full cost (incl.&nbsp;overhead)</td>
<td style="text-align: right;">$ 9.00</td>
</tr>
<tr class="even">
<td>Profit</td>
<td style="text-align: right;">$ 9.00</td>
</tr>
<tr class="odd">
<td><strong>Price (per dose)</strong></td>
<td style="text-align: right;"><strong>$18.00</strong></td>
</tr>
</tbody>
</table>
<p>Is this an informative price?</p>
</section>
<section id="cost-allocation-is-an-old-question" class="slide level2">
<h2>Cost allocation is an old question</h2>
<blockquote>
<p>Indirect expense is one of the most important of all the accounts appearing on the books of the manufacturer. Methods of handling its [allocation] have given rise to more arguments than the descent of man. It is the rock upon which many a ship of industry has been wrecked.</p>
</blockquote>
<ul>
<li>Thompson (1916)</li>
</ul>
</section>
<section id="consider-a-manufacturing-firm" class="slide level2">
<h2>Consider a manufacturing firm</h2>
<p>May have many different allocation processes for a single product.</p>
<ul>
<li>Taxes (one set of depreciations, and FC allocations)</li>
<li>Financial reporting</li>
<li>Government contracts</li>
<li>Other contracts</li>
<li>Internal incentives</li>
<li>Internal cost control</li>
</ul>
</section>
<section id="reasons-to-allocate-costs" class="slide level2 scrollable">
<h2>Reasons to allocate costs</h2>
<ol type="1">
<li>External reporting (IFRS, GAAP, also fraud)</li>
<li>Taxes</li>
<li>Cost-based contracts (esp.&nbsp;gov contracting)</li>
<li>Decision making</li>
<li>Incentives and accountability (‘control’)</li>
</ol>
</section>
<section id="a-footnote-about-fraud" class="slide level2">
<h2>A footnote about fraud</h2>
<p><strong>Fraud is a financial accounting act, but a managerial accounting choice</strong></p>
<ul>
<li>It is the act of <em>misreporting</em> which is illegal.</li>
<li>However, without a performance incentive (explicit or implicit) misreporting is unlikely.</li>
<li>Gambling for resurrection at FedEx.
<ul>
<li>Investigation of the <em>precursors</em> of financial crimes at Goldman.</li>
<li>Enron and Arthur Anderson (audit business was marketing for software business).</li>
<li>Are you paying accountants for high-quality financial statements? Or to write down the numbers that shareholders and regulators want to see?</li>
</ul></li>
</ul>
</section>
<section id="incentive-effects-of-cost-allocations" class="slide level2">
<h2>Incentive effects of cost allocations</h2>
<ul>
<li>Cost allocations modify behavior a la <a href="https://en.wikipedia.org/wiki/Pigouvian_tax">Pigouvian taxes</a>.</li>
<li><strong>All cost allocations, like all taxes, modify behavior</strong>. They are never neutral.</li>
</ul>
</section>
<section id="pigouvian-tax" class="slide level2">
<h2>Pigouvian tax</h2>

<img data-src="pigtax.png" style="width:50.0%" class="r-stretch quarto-figure-center"><p class="caption">Using a tax to modify behavior</p></section>
<section id="why-do-we-have-common-costs" class="slide level2">
<h2>Why do we have common costs?</h2>
<ul>
<li>The tax analogy helps us think about why cost allocations might be useful/harmful.</li>
<li>But this reasoning doesn’t explain why we are ‘taxing’ aspirin in the hospital example.</li>
<li>Common costs arise when it is less expensive to provide a good or service centrally (synergy).</li>
</ul>
<p><em>We are trying to communicate information about the costs and benefits (synergy) of coopertative resource allocation within the firm.</em></p>
</section>
<section id="consider-the-following" class="slide level2">
<h2>Consider the following:</h2>
<ul>
<li>A firm manufactures spinning hard drives and solid state hard drives</li>
<li>The two divisions share a building but are separate profit centers</li>
<li>Managers are compensated based on profits</li>
</ul>
</section>
<section id="how-do-we-treat-common-costs" class="slide level2">
<h2>How do we treat common costs?</h2>
<!-- TODO: concrete examples here -->
<ul>
<li>If we deduct common costs from the manager’s profits they will try to reduce common costs
<ul>
<li>Use too little IT services.</li>
</ul></li>
<li>If we do not, then they will demand more of the common resources
<ul>
<li>Use too much IT services.</li>
</ul></li>
</ul>
</section>
<section id="how-do-we-treat-common-costs-1" class="slide level2">
<h2>How do we treat common costs?</h2>
<ul>
<li>What we choose will depend on whether the managers can control their consumption of the common costs.
<ul>
<li>Allocation of the factory itself?</li>
<li>Allocation of cleaning crew?</li>
<li>Allocation of IT?</li>
</ul></li>
<li>Allocating common costs is widespread, so overconsumption of common resources seems to be a common concern.</li>
</ul>
</section>
<section id="allocating-common-costs" class="slide level2">
<h2>Allocating common costs</h2>
<h3 id="how-should-we-interpret-the-status-quo">How should we interpret the <em>status quo</em>?</h3>
<p><em>“Most firms allocate common costs, presumably to prevent individual divisions from overconsuming the common resource.”</em> (Zimmerman Textbook)</p>
<ul>
<li>and yet, forcing firms to adopt cost accounting systems improves their performance, suggesting that <em>some</em> firms may just be using allocations from financial or tax accounting. (<a href="https://publications.aaahq.org/accounting-review/article/96/1/401/4242/Government-Procurement-and-Changes-in-Firm">Samuels, 2021</a>)</li>
</ul>
</section>
<section id="allocating-common-costs-1" class="slide level2 scrollable">
<h2>Allocating common costs</h2>
<ul>
<li><strong>Common costs:</strong> arise when it is less expensive to provide an internal product or service centrally.</li>
<li><strong>Consider:</strong> the two divisions of the hard drive manufacturer (SSD and HHD) share:</li>
</ul>
<ol type="1">
<li>building maintenance</li>
<li>grounds</li>
<li>property taxes security</li>
<li>human resources department</li>
</ol>
</section>
<section id="allocating-common-costs-2" class="slide level2 scrollable">
<h2>Allocating common costs</h2>
<h3 id="questions">Questions:</h3>
<ol type="1">
<li>Should the common costs be allocated to the manufacturing divisions?</li>
<li>If so, how?</li>
</ol>
<p><em>The remainder of the semester is focused on this latter question.</em></p>
</section>
<section id="allocating-common-costs-3" class="slide level2 scrollable">
<h2>Allocating common costs</h2>
<h3 id="considerations">Considerations:</h3>
<ol type="1">
<li>division managers get paid for their division’s accounting profit</li>
<li>cost allocations act like taxes and affect the managers’ welfare, and their behavior.</li>
<li>if allocated, managers will seek to reduce costs by improving processes, cutting corners, or claiming not to need or use the common resource</li>
<li>if not allocated, managers will seek to maximize use of the common resources</li>
</ol>
</section>
<section id="allocating-common-costs-4" class="slide level2">
<h2>Allocating common costs</h2>
<p>So how do we go about this?</p>
</section>
<section id="to-allocate-we-need-an-allocation-basecost-driver" class="slide level2">
<h2>To allocate we need an <em>allocation base/cost driver</em>:</h2>
<p>An allocation base or cost driver is the metric used to allocate costs (like the aspirin in the hospital example).</p>
<ul>
<li>Choosing an allocation base is one of the most important topics in all of accounting. Choosing correctly requires analysis of processes, data, and incentives.</li>
<li>This focus on this critical aspect of accounting is missing from most texts and this course.</li>
<li>In this lecture we will consider the consequences of these choices.</li>
</ul>
</section>
<section id="insulating-and-non-insulating-allocations" class="slide level2">
<h2>Insulating and non-insulating allocations</h2>
<ul>
<li>the choice of driver can either <em>insulate</em> the manager’s pay from the cost or not.</li>
</ul>
</section>
<section id="a.-non-insulating-method" class="slide level2">
<h2><strong>A. Non-insulating method</strong></h2>
<p>A noninsulating method uses a driver that varies with the manager’s performance measures (e.g.&nbsp;div. operating income)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Jan.&nbsp;HDD</th>
<th>Jan.&nbsp;SSD</th>
<th>Feb.&nbsp;HHD</th>
<th>Feb.&nbsp;SSD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Div. Op. Income</td>
<td>$8,000</td>
<td>$8,000</td>
<td>$9,000</td>
<td>$2,000</td>
</tr>
<tr class="even">
<td>Allocated costs</td>
<td>(800)</td>
<td>(800)</td>
<td>(900)</td>
<td>(200)</td>
</tr>
<tr class="odd">
<td>Net income</td>
<td>$7,200</td>
<td>$7,200</td>
<td>$8,100</td>
<td>$1,800</td>
</tr>
</tbody>
</table>
<p>This is a tax on operating income.</p>
</section>
<section id="b.-insulating-method" class="slide level2">
<h2><strong>B. Insulating method</strong></h2>
<p>An insulating allocation uses a driver that does not vary with the manager’s performance measures (e.g.&nbsp;floorspace).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Jan.&nbsp;HDD</th>
<th>Jan.&nbsp;SSD</th>
<th>Feb.&nbsp;HHD</th>
<th>Feb.&nbsp;SSD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Div. Op. Income</td>
<td>$8,000</td>
<td>$8,000</td>
<td>$9,000</td>
<td>$2,000</td>
</tr>
<tr class="even">
<td>Allocated costs</td>
<td>(600)</td>
<td>(400)</td>
<td>(600)</td>
<td>(400)</td>
</tr>
<tr class="odd">
<td>Net income</td>
<td>$7,400</td>
<td>$7,600</td>
<td>$8,400</td>
<td>$1,600</td>
</tr>
</tbody>
</table>
<p>This is a tax on floorspace.</p>
</section>
<section id="what-we-prefer-depends-on-what-information-we-want-to-communicate" class="slide level2">
<h2>What we prefer depends on what information we want to communicate</h2>
<ul>
<li>Is it better to tax income or floorspace?</li>
<li>This depends on what the objectives are and what the manager has control over.</li>
<li>Do we want the manager to maximize income?</li>
<li>Or do we want the manager to minimize floorspace?</li>
</ul>
</section>
<section id="allocations-in-practice" class="slide level2">
<h2>Allocations in practice</h2>
<ul>
<li>The allocation bases chosen (what to tax) affect the use of resources inside the firm.</li>
<li>Cost allocations also create incentives to cooperate.</li>
<li>Cost allocations can distort reported performance</li>
</ul>
<!-- - This is another example of how accounting systems tend to favor control when -->
<p><!-- confronted with a choice between control and decision making. --> <!-- - This doesn't mean that it is the optimal decision. --></p>
</section>
<section id="allocating-service-department-costs" class="slide level2">
<h2>Allocating service department costs</h2>
<p>Now that we’re clear on all the things that can go wrong, lets try to do it!</p>
</section>
<section id="allocating-service-department-costs-1" class="slide level2">
<h2>Allocating service department costs</h2>

<img data-src="alloc.png" style="width:75.0%" class="r-stretch quarto-figure-center"><p class="caption">Usage flows among N service departments and M production departments.</p></section>
<section id="example" class="slide level2">
<h2>Example:</h2>
<p><strong>Capacity of service departments used:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Telecoms</th>
<th>IT</th>
<th>Cars</th>
<th>Trucks</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>10%</td>
<td>20%</td>
<td>40%</td>
<td>30%</td>
<td>100%</td>
</tr>
<tr class="even">
<td>IT</td>
<td>25%</td>
<td>15%</td>
<td>35%</td>
<td>25%</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p><strong>Service department costs:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>2,000,000</td>
</tr>
<tr class="even">
<td>IT</td>
<td>6,000,000</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>8,000,000</td>
</tr>
</tbody>
</table>
</section>
<section id="direct-method" class="slide level2">
<h2>Direct method</h2>
</section>
<section id="service-dept-actual-usage-allocation" class="slide level2">
<h2>Service dept actual usage allocation:</h2>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Cars</th>
<th>Trucks</th>
<th>Tot Alloc</th>
<th>Tot Incur</th>
<th>Tot Unalc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>$0.8</td>
<td>$0.6</td>
<td>$1.4</td>
<td>$2.0</td>
<td>$0.6</td>
</tr>
<tr class="even">
<td></td>
<td>(40% <span class="math inline">\(\times\)</span> $2)</td>
<td>(30% <span class="math inline">\(\times\)</span> $2)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>IT</td>
<td>$2.1</td>
<td>$1.5</td>
<td>$3.6</td>
<td>$6.0</td>
<td>$2.4</td>
</tr>
<tr class="even">
<td></td>
<td>(35% <span class="math inline">\(\times\)</span> $6)</td>
<td>(25% <span class="math inline">\(\times\)</span> $6)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td></td>
<td></td>
<td>$5.0</td>
<td>$8.0</td>
<td>$3.0</td>
</tr>
</tbody>
</table>
<p><em>(Dollars are in millions)</em></p>
</section>
<section id="direct-allocation-method" class="slide level2">
<h2>Direct allocation method:</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 36%">
<col style="width: 35%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Shares</strong></th>
<th>Cars</th>
<th>Trucks</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>40%/(40% + 30%) = 4/7</td>
<td>30%/(40% + 30%) = 3/7</td>
<td>100%</td>
</tr>
<tr class="even">
<td>IT</td>
<td>35%/(35% + 25%) = 7/12</td>
<td>25%/(35% + 25%) = 5/12</td>
<td>100%</td>
</tr>
</tbody>
</table>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 24%">
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Allocated Costs</strong></th>
<th style="text-align: right;">Cars</th>
<th style="text-align: right;">Trucks</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td style="text-align: right;">4/7 <span class="math inline">\(\times\)</span> $2 = $1.143</td>
<td style="text-align: right;">3/7 <span class="math inline">\(\times\)</span> $2 = $0.857</td>
<td>$2</td>
</tr>
<tr class="even">
<td>IT</td>
<td style="text-align: right;">7/12 <span class="math inline">\(\times\)</span> $6 = $3.5</td>
<td style="text-align: right;">5/12 <span class="math inline">\(\times\)</span> $6 = $2.5</td>
<td>$6</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">$4.643</td>
<td style="text-align: right;">$3.357</td>
<td>$8</td>
</tr>
</tbody>
</table>
</section>
<section id="good-news-bad-news" class="slide level2">
<h2>Good news, Bad news</h2>
<ul>
<li><strong>Good news:</strong> everything is allocated</li>
<li><strong>Bad news:</strong> this is not a good estimate of opportunity cost per unit of service</li>
</ul>
</section>
<section id="what-we-know" class="slide level2">
<h2>What we know:</h2>
<p>While we do not know the correct opportunity cost, we do know that the <strong>direct allocation method excludes the service departments’ use of other service departments</strong> and therefore incorrectly states the opportunity cost of each service department.</p>
</section>
<section id="step-down-method" class="slide level2">
<h2>Step-down method</h2>

<img data-src="step.png" style="width:50.0%" class="r-stretch quarto-figure-center"><p class="caption">The step-down method</p></section>
<section id="step-down-shares-start-w-tele" class="slide level2">
<h2>Step-down shares (start w/ Tele)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">IT</th>
<th style="text-align: right;">Cars</th>
<th style="text-align: right;">Trucks</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td style="text-align: right;">20%/(20% + 40% + 30%)</td>
<td style="text-align: right;">40%/90%</td>
<td style="text-align: right;">30%/90%</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">= 2/9</td>
<td style="text-align: right;">= 4/9</td>
<td style="text-align: right;">= 1/3</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>IT</td>
<td style="text-align: right;">None</td>
<td style="text-align: right;">35%/60%</td>
<td style="text-align: right;">25%/60%</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">= 7/12</td>
<td style="text-align: right;">= 5/12</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p><em>In this step we allocate the cost of Telecoms to <strong>IT</strong>, Cars, and Trucks. So <strong>IT</strong> includes the cost of Telecoms when we allocate it to Cars and Trucks.</em> We use these shares to allocate costs on the next slide.</p>
</section>
<section id="step-down-allocations" class="slide level2">
<h2>Step-down allocations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Costs to Allocate</th>
<th style="text-align: right;">IT</th>
<th style="text-align: right;">Cars</th>
<th style="text-align: right;">Trucks</th>
<th>Total Alloc.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Telecoms</td>
<td style="text-align: right;">$2</td>
<td style="text-align: right;">2/9 <span class="math inline">\(\times\)</span> $2</td>
<td style="text-align: right;">4/9 <span class="math inline">\(\times\)</span> $2</td>
<td style="text-align: right;">1/3 <span class="math inline">\(\times\)</span> $2</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">= $0.444</td>
<td style="text-align: right;">= $0.889</td>
<td style="text-align: right;">= $0.667</td>
<td>$1.556</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IT</td>
<td style="text-align: right;">$6 + $0.444</td>
<td style="text-align: right;">None</td>
<td style="text-align: right;">7/12 <span class="math inline">\(\times\)</span> $6.444</td>
<td style="text-align: right;">5/12 <span class="math inline">\(\times\)</span> $6.444</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">= $3.759</td>
<td style="text-align: right;">= $2.685</td>
<td>$6.444</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">$4.648</td>
<td style="text-align: right;">$3.352</td>
<td>$8.000</td>
</tr>
</tbody>
</table>
</section>
<section id="does-the-order-matter" class="slide level2">
<h2>Does the order matter?</h2>
<p>It may! In this case the difference in magnitudes is relatively minor.</p>
</section>
<section id="step-down-shares-start-w-it" class="slide level2">
<h2>Step-down shares (start w/ IT)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Telecoms</th>
<th style="text-align: right;">Cars</th>
<th style="text-align: right;">Trucks</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IT</td>
<td style="text-align: right;">25%+/(25% + 35% + 25%)</td>
<td style="text-align: right;">35%/85%</td>
<td style="text-align: right;">25%/85%</td>
<td>100%</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">= 5/17</td>
<td style="text-align: right;">= 7/17</td>
<td style="text-align: right;">= 5/17</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>Telecoms</td>
<td style="text-align: right;">None</td>
<td style="text-align: right;">4/7</td>
<td style="text-align: right;">3/7</td>
<td>100%</td>
</tr>
</tbody>
</table>
</section>
<section id="step-down-allocations-1" class="slide level2">
<h2>Step-down allocations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Costs to Allocate</th>
<th style="text-align: right;">IT</th>
<th style="text-align: right;">Cars</th>
<th style="text-align: right;">Trucks</th>
<th>Total Alloc.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IT</td>
<td style="text-align: right;">$6</td>
<td style="text-align: right;">5/17 <span class="math inline">\(\times\)</span> $6</td>
<td style="text-align: right;">7/17 <span class="math inline">\(\times\)</span> $6</td>
<td style="text-align: right;">5/17 <span class="math inline">\(\times\)</span> $6</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">= $1.765</td>
<td style="text-align: right;">= $2.470</td>
<td style="text-align: right;">= $ 1.765</td>
<td>$4.235</td>
</tr>
<tr class="odd">
<td>Telecoms</td>
<td style="text-align: right;">$2 + $1.765</td>
<td style="text-align: right;">None</td>
<td style="text-align: right;">4/7 <span class="math inline">\(\times\)</span> $3.765</td>
<td style="text-align: right;">317 <span class="math inline">\(\times\)</span> $3.765</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">= $ 2.151</td>
<td style="text-align: right;">= $ 1.614</td>
<td>$3.765</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">$4.6210</td>
<td style="text-align: right;">$3.379</td>
<td>$8.000</td>
</tr>
</tbody>
</table>
<p><em>costs are in millions.</em></p>
</section>
<section id="does-the-order-matter-1" class="slide level2">
<h2>Does the order matter?</h2>
</section>
<section id="does-the-order-matter-2" class="slide level2">
<h2>Does the order matter?</h2>
<ul>
<li>The costs allocated to Cars and Trucks differ by only $27,000 depending on whether telecommunications or IT is chosen first.<br>
</li>
<li>The difference of $27,000 is less than 1 percent of the total costs allocated.</li>
</ul>
</section>
<section id="does-the-order-matter-3" class="slide level2">
<h2>Does the order matter?</h2>
<ul>
<li>However, very different incentives result depending on which method is used.</li>
<li>Allocated costs are taxes, and taxes effect behavior.</li>
<li>And these can lead to the <strong>Death Spiral</strong> if the tax is too high!</li>
</ul>
</section>
<section id="illustration" class="slide level2">
<h2>Illustration:</h2>
<ul>
<li>To illustrate lets expand the telecommunications and IT example.</li>
<li>Suppose the allocation base in telecommunications is the number of telephones in each department, and</li>
<li>in IT the allocation base is the number of gigabytes of disk space used.</li>
</ul>
</section>
<section id="illustration-1" class="slide level2">
<h2>Illustration:</h2>
<ul>
<li>Transfer prices are to be established for telephones and gigabytes.</li>
<li>Allocated costs will be used to compute the transfer prices.</li>
</ul>
</section>
<section id="the-allocation-bases" class="slide level2">
<h2>The allocation bases:</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Allocation base</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecomm</td>
<td>3,000 Telephones</td>
</tr>
<tr class="even">
<td>IT</td>
<td>12 million gigabytes</td>
</tr>
</tbody>
</table>
<!-- if there was more appitite for data analysis we sould spend a lot more time on teh critical question of how best to actually choose allocation bases. -->
</section>
<section id="cost-allocated-per-phone" class="slide level2">
<h2>Cost allocated per phone</h2>
<h4 id="number-of-phones">Number of phones</h4>
<table class="caption-top">
<colgroup>
<col style="width: 10%">
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Direct</th>
<th>Step, Telecomm first</th>
<th>Step, IT first</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>–</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="even">
<td>IT</td>
<td>–</td>
<td>20% <span class="math inline">\(\times\)</span> 3,000 = 600</td>
<td>–</td>
</tr>
<tr class="odd">
<td>Cars</td>
<td>40% <span class="math inline">\(\times\)</span> 3,000 = 1,200</td>
<td>40% <span class="math inline">\(\times\)</span> 3,000 = 1,200</td>
<td>40% <span class="math inline">\(\times\)</span> 3,000 = 1,200</td>
</tr>
<tr class="even">
<td>Trucks</td>
<td>30% <span class="math inline">\(\times\)</span> 3,000 = 900</td>
<td>30% <span class="math inline">\(\times\)</span> 3,000 = 900</td>
<td>30% <span class="math inline">\(\times\)</span> 3,000 = 900</td>
</tr>
<tr class="odd">
<td>Phones</td>
<td>2,100</td>
<td>2,700</td>
<td>2,100</td>
</tr>
</tbody>
</table>
<ul>
<li><em>Note: that telecom is always ‘–’ here because we are considering how to allocate it’s costs. The in the ‘IT first’ column the telecom costs already include IT costs.</em></li>
</ul>
</section>
<section id="cost-allocated-per-phone-1" class="slide level2">
<h2>Cost allocated per phone</h2>
<table class="caption-top">
<colgroup>
<col style="width: 34%">
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Direct</th>
<th>Step, Telecomm first</th>
<th>Step, IT first</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cost per phone</td>
<td>$2M/2,100</td>
<td>$2M/2,700</td>
<td>$3.765M/2,100</td>
</tr>
<tr class="even">
<td></td>
<td>= $ 952</td>
<td>= $ 741</td>
<td>= $1.793</td>
</tr>
<tr class="odd">
<td>Number of phones: Cars</td>
<td>1,200</td>
<td>1,200</td>
<td>1,200</td>
</tr>
<tr class="even">
<td>Telecoms charged to Cars</td>
<td>$1.143</td>
<td>$0.889</td>
<td>$ 2.151</td>
</tr>
</tbody>
</table>
</section>
<section id="does-the-order-matter-4" class="slide level2">
<h2>Does the order matter?</h2>
<p>The order can lead to large changes in the ‘tax’ on the allocation base!</p>
</section>
<section id="cost-allocated-per-gigabyte-of-storage" class="slide level2">
<h2>Cost allocated per Gigabyte of Storage</h2>
<h4 id="number-of-gigabytes-of-storage">Number of Gigabytes of Storage</h4>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Direct</th>
<th>Step, Telecomm first</th>
<th>Step, IT first</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telecoms</td>
<td>–</td>
<td>–</td>
<td>25% <span class="math inline">\(\times\)</span> 12 = 3.0</td>
</tr>
<tr class="even">
<td>IT</td>
<td>–</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="odd">
<td>Cars</td>
<td>35% <span class="math inline">\(\times\)</span> 12 = 4.2</td>
<td>35% <span class="math inline">\(\times\)</span> 12 = 4.2</td>
<td>35% <span class="math inline">\(\times\)</span> 12 = 4.2</td>
</tr>
<tr class="even">
<td>Trucks</td>
<td>25% <span class="math inline">\(\times\)</span> 12 = 3.0</td>
<td>25% <span class="math inline">\(\times\)</span> 12 = 3.0</td>
<td>25% <span class="math inline">\(\times\)</span> 12 = 3.0</td>
</tr>
<tr class="odd">
<td>Gigs</td>
<td>7.2</td>
<td>7.2</td>
<td>10.2</td>
</tr>
</tbody>
</table>
<ul>
<li><em>Note: that IT is always ‘–’ here because we are considering how to allocate it’s costs. The in the ‘Telecom first’ column the IT costs already include Telecom costs.</em></li>
</ul>
</section>
<section id="cost-allocated-per-gigabyte-of-storage-1" class="slide level2">
<h2>Cost allocated per Gigabyte of Storage</h2>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Direct</th>
<th>Step, Telecomm first</th>
<th>Step, IT first</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cost per gig</td>
<td>$6/7.2 = $0.833</td>
<td>$6.44/7.2 = $0.895</td>
<td>$6/10.2 = $0.588</td>
</tr>
<tr class="even">
<td>Number of gigs in Cars</td>
<td>4.2</td>
<td>4.2</td>
<td>4.2</td>
</tr>
<tr class="odd">
<td>IT charged to Cars</td>
<td>$3.5</td>
<td>$3.759</td>
<td>$2.470</td>
</tr>
</tbody>
</table>
<h5 id="cost-allocated-per-giga-of-storage-millions-except-cost-per-gb">Cost allocated per Giga of storage (Millions except cost per Gb)</h5>
</section>
<section id="consider-the-impact-on-behavior" class="slide level2">
<h2>Consider the impact on behavior:</h2>
<ul>
<li>The sequence of service departments in the step-down method changes the costs of each service.</li>
<li>Because the cost per phone (which represents the transfer price) varies depending whether or not it includes IT costs,</li>
<li>the cost allocation scheme affects the decision of each department to add or drop phones.</li>
<li>The same conclusions hold for the information technology department.</li>
</ul>
</section>
<section id="does-the-order-matter-5" class="slide level2">
<h2>Does the order matter?</h2>
<ul>
<li>Note the wide variation in cost per gigabyte.</li>
<li>The cost varies from $0.588 per gigabyte under the step-down method with IT chosen first</li>
<li>to $0.895 under the step-down method with telecommunications chosen first.</li>
</ul>
<!-- However, these same methods cause the cost-based transfer prices to vary by more than 140 percent for telephones (I $1,793 ÷ $741] ÷ $741) and more than 50 percent for gigabytes ([$0.895 ÷ $0.5881 ÷ $0.588). Why the discrepancy? Refer back to L Table 8-1. In this example, the Cars division uses roughly equal fractions of the two service departments (57 percent and 58 percent), and the Trucks division uses roughly equal fractions of the service departments (43 percent and 42 percent). Because these fractions are roughly the same in both departments, the total costs allocated to the divisions vary little across the various methods. However, the transfer prices per phone and gigabyte vary dramatically. In general, the allocation methods can yield substantial differences in amounts allocated. The numbers chosen for this example illustrate that transfer prices can vary greatly even when the cost allocation methods have little effect on the total amounts allocated. -->
</section>
<section id="the-central-issues-with-the-step-down-method" class="slide level2">
<h2>The central issues with the step-down method:</h2>
<ul>
<li>The sequence used is arbitrary and large differences can result in the cost per unit of service using different sequences.</li>
<li>Also, the step-down method ignores the fact that although departments earlier in the sequence use service departments later in the sequence, earlier departments are not allocated these costs.</li>
<li>Get this wrong and risk the death spiral.</li>
</ul>
</section>
<section id="death-spiral" class="slide level2">
<h2>Death spiral</h2>
<ul>
<li>A feedback loop leading to inefficient outcomes, sometimes bankruptcy.</li>
<li>Result of ‘cost’ reduction incentives, which do not actually reduce costs.</li>
<li>Arise when common costs consist primarily of fixed costs and users have discretion over their use of the common product or service.</li>
</ul>
</section>
<section id="steps-in-the-death-spiral" class="slide level2 scrollable">
<h2>Steps in the death spiral:</h2>
<ol type="1">
<li>The death spiral occurs when cost allocation reduces utilization of a common resource (with significant fixed costs).
<ul>
<li>i.e.&nbsp;the common cost is taxed, so it’s utilization falls.</li>
</ul></li>
<li>This creates excess capacity. Now the fixed cost is spread over fewer units of the allocation base.</li>
<li>This increases the allocation rate for the remaining users (increasing the ‘tax’ rate), which further reduces utilization.</li>
</ol>
</section>
<section id="death-spiral-not-literal-in-corporate-jets" class="slide level2">
<h2>Death Spiral (not literal) in Corporate Jets</h2>
<ul>
<li>The annual operating cost of a corporate jet ranges between $40 and $50 million.</li>
<li>Corporate flight departments routinely charge part or all of these costs to those internal departments using the aircraft.</li>
<li>Allocating operating costs to internal users allows flight departments to justify the expense of the aircraft to top management, to apportion operating costs according to usage patterns, and to prevent overscheduling.</li>
</ul>
</section>
<section id="death-spiral-not-literal-in-corporate-jets-1" class="slide level2">
<h2>Death Spiral (not literal) in Corporate Jets</h2>
<ul>
<li>Initially, only the direct operating costs (fuel and landing fees) were charged back to departments using the aircraft, while fixed costs were not (pilot salaries, maintenance costs, hangar rental, and insurance).</li>
</ul>
<p>These costs are all variable, so no (figurative) danger</p>
</section>
<section id="death-spiral-not-literal-in-corporate-jets-2" class="slide level2">
<h2>Death Spiral (not literal) in Corporate Jets</h2>
<ul>
<li>When firms faced downturns in their business, a popular expense reduction target was to cut corporate jet usage by allocating the fixed costs along with the direct costs of operating the aircraft.</li>
</ul>
<p>This makes sense, but now we are allocating fixed costs, and managers can choose how much to use! <strong>But their choice does not change the fixed costs.</strong></p>
</section>
<section id="death-spiral-not-literal-in-corporate-jets-3" class="slide level2">
<h2>Death Spiral (not literal) in Corporate Jets</h2>
<ul>
<li>Since fixed costs accounted for about 50 percent of the total cost at <strong>full utilization</strong>, usage rapidly shrank to the point where fixed costs rose to 85 percent of the total allocated cost.</li>
</ul>
<p>What happens when taxes go up?</p>
</section>
<section id="death-spiral-not-literal-in-corporate-jets-4" class="slide level2">
<h2>Death Spiral (not literal) in Corporate Jets</h2>
<ul>
<li>Jet usage dropped further, and each flight hour allocated became even more costly, sometimes approaching the cost of chartering a jet.</li>
<li>At this point there is no economy of scale and no reason to produce the service internally!</li>
</ul>
</section>
<section id="can-we-avoid-this" class="slide level2">
<h2>Can we avoid this?</h2>
<ul>
<li>When there is excess capacity only allocate the variable cost of the resource.</li>
<li>Alternatively, some of the fixed costs could be excluded from the transfer price.</li>
<li>Using practical capacity instead of actual utilization in calculating the overhead rate.</li>
</ul>
</section>
<section id="a-caution" class="slide level2">
<h2>A caution:</h2>
<p>If you are not careful, you might use arithmetic to convince yourself that adding new products or services may <strong>decrease fixed costs</strong>.</p>
<p>No production decision, other than actually changing the fixed costs themselves, can change fixed costs.</p>
</section>
<section id="allocating-capacity-cost-depreciation" class="slide level2">
<h2>Allocating capacity cost: depreciation</h2>
<ul>
<li>Not allocating some (or all) of the fixed cost can reduce the death spiral.</li>
<li>For example, allocate only the fixed cost of the capacity actually being used.</li>
<li>If 40 percent excess capacity exists, allocate only 60 percent of the depreciation.</li>
<li>However, this solution to the death spiral creates other concerns.</li>
</ul>
</section>
<section id="allocating-capacity-cost-depreciation-1" class="slide level2">
<h2>Allocating capacity cost: depreciation</h2>
<ul>
<li>How much of the existing common resource should each user use?</li>
<li>The current capacity level was chosen for some reason!</li>
<li>If excess capacity exists, any charge discourages its use.</li>
<li>Allocating accounting depreciation to users commits them to recovering at least the historical cost of the asset.</li>
</ul>
</section>
<section id="the-trade-off" class="slide level2">
<h2>The trade-off</h2>
<p>When allocating depreciation the firm trades off:</p>
<ul>
<li>the efficient investment in the common resource and</li>
<li>its efficient utilization after acquisition.</li>
</ul>
</section>
<section id="on-one-hand-on-the-other-hand" class="slide level2">
<h2>On one hand… on the other hand:</h2>
<p>Charging depreciation helps control the overinvestment problem, but at the expense of underutilizing the asset after acquisition.</p>
<p>Most firms charge users for depreciation.</p>
</section>
<section id="control-of-overinvestment-is-the-habit-of-financial-accounting-systems" class="slide level2">
<h2>Control of overinvestment is the <em>habit</em> of financial accounting systems</h2>
<ul>
<li>Full absorption costing allocates fixed costs, and is the default accounting system. <!-- - Allocation of fixed costs addresses the overinvestment problem. --></li>
<li>Control of the overinvestment problem dominates decision-making by default.</li>
<li>Thus, errors involving asset under-utilization (the death spiral) are the probable failure mode.</li>
</ul>
<p><em>Next week we will try to improve on the step-down method.</em></p>
</section>
<section id="two-examples-if-there-is-time" class="slide level2">
<h2>Two Examples (if there is time)</h2>
</section>
<section id="step-down-allocations-and-medicare" class="slide level2">
<h2>Step-Down Allocations and Medicare</h2>
</section>
<section id="step-down-allocations-and-medicare-1" class="slide level2">
<h2>Step-Down Allocations and Medicare</h2>
<ul>
<li>The U.S. Medicare system requires each hospital to file a Medicare Cost Report to get reimbursed for providing health care to Medicare patients.</li>
<li>To file this report, all cost centers in the hospital (administration, finance, human resources) that supply services to other cost centers and major functional services, such as the emergency department, surgery, and maternity, are ordered in a step-down sequence.</li>
</ul>
</section>
<section id="step-down-allocations-and-medicare-2" class="slide level2">
<h2>Step-Down Allocations and Medicare</h2>
<ul>
<li>Each cost center allocates its cost using an allocation base.</li>
<li>For example, nursing administration costs might be allocated using nursing hours or nursing salaries in each functional service.</li>
</ul>
</section>
<section id="step-down-allocations-and-medicare-3" class="slide level2">
<h2>Step-Down Allocations and Medicare</h2>
<ul>
<li>The Medicare Cost Report defines the order of the cost centers to be used in the step-down method but allows each hospital some discretion.</li>
<li>For example, administration and general costs are usually allocated last. -However, some hospitals move it up in the list.</li>
</ul>
</section>
<section id="step-down-allocations-and-medicare-4" class="slide level2">
<h2>Step-Down Allocations and Medicare</h2>
<ul>
<li>The step-down method allocates the cost of each service center, as well as the costs stepped down to it, to the major functional services.</li>
<li>Many hospitals use the data generated by the Medicare Cost Report to set prices and to negotiate third-party contracts.</li>
<li><strong>Note that the Medicare system is one of the few parts of the US health system that actually works!</strong></li>
</ul>
<p>SOURCE: M. Muse and B. Amoia, “Step Up to the Step-Down Method,” Healthcare Financial Management, May 2006.</p>
</section>
<section id="next-class" class="slide level2">
<h2>Next class</h2>
<p>We will try to improve on the step-down method.</p>
<!-- - Reciprocal allocations -->
<!-- # Joint costs -->
<!-- ## Joint costs and the death spiral -->
<!---->
<!-- ## Net realizable value -->
<!---->
<!-- ## Decision making and control -->
</section>
<section id="getting-this-right-matters-lenovo" class="slide level2">
<h2>Getting this right matters! (Lenovo)</h2>
<ul>
<li>Who has used a Lenovo ThinkPad?</li>
</ul>
</section>
<section id="example-cost-allocations-at-ibm" class="slide level2">
<h2>Example: Cost Allocations at IBM:</h2>
<p>During the 1980s and early 1990s, IBM had the policy of allocating costs from one line of business to another. Managers in those lines of business constantly argued that some of their overhead should be carried by other IBM businesses.</p>
</section>
<section id="example-cost-allocations-at-ibm-1" class="slide level2">
<h2>Example: Cost Allocations at IBM:</h2>
<p>IBM also typically allocated all of the R&amp;D of a new technology to the line of business first using the technology, and subsequent users were able to utilize it for free.</p>
</section>
<section id="example-cost-allocations-at-ibm-2" class="slide level2">
<h2>Example: Cost Allocations at IBM:</h2>
<p>This cost allocation system masked the true profitability of many IBM businesses for years. IBM claimed it was making money in its PC business.</p>
</section>
<section id="example-cost-allocations-at-ibm-3" class="slide level2">
<h2>Example: Cost Allocations at IBM:</h2>
<p>But in 1992, “as IBM began to move away from its funny allocation system, IBM disclosed that its PC business was unprofitable.” In 2004, IBM sold its PC division to China-based Lenovo Group for $1.75 billion.</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="costallocation_slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="costallocation_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="costallocation_slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="costallocation_slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>